### PR TITLE
Debugger

### PR DESCRIPTION
**Pull request by zoriya**
Adding a disassembly viewer inside the CPU's debugger.
Removed the switch case for the execute Instruction to use an array with pointer to methods instead.

### CODE REVIEW

**Review by melefo — COMMENTED** [review]
Everything looks good!

**Review by Octopus773 — APPROVED** [review]
Nothing looks too shaggy/shady

**Review by melefo — APPROVED** [review]
Approved!

**Review by Octopus773 — APPROVED** [review]
Nothing looks too Shaggy/Shady

**Pull request merged**
